#모의투자

APP_KEY: "PSWVRfqReJTEfl5f1pOKEsUoopd1UN5p8hEm"
APP_SECRET: "nKK6AbcQpJ7kd5wbtxoGquNFmTR10uuTJoaTwhYQX0SdCoy1ZxrUOSSXPlOddq1rOgf3FqYRktcBBfh4Rurr593kqQs1FLL/k9zVIetbaidyc7nbPR60bRJmdYpO2tfSTJzbK4VCo/eWED6sCbZqwlfMTTaGSVHpEzJJ7yyXK/Cwva5GWEc="

#계좌번호 앞 8자리
CANO: "50114760"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

URL_BASE: "https://openapivts.koreainvestment.com:29443"


#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#실전투자

#APP_KEY: "PS1n0S2m2cOKp1sO28wX9N4euaWcqfPaOrB3"
#APP_SECRET: "1jHIwmajfHWegLPZpRa2FDybxaenRg8BsqfR0r2uXWvPC47Q4WOlGpnNibczZXoDJoqA2KyqZUb9HofRtSd0+wxHdMDSx5bMMM18mhQMeBdkUuJvmbXmIDtoJ7G16dClKqQbQ9/e8zb2Xch0OI1e2PMBkNCdUaQE3ASj8CE66YMw0WvbJ+Q="

#계좌번호 앞 8자리
#CANO: "69419519"
#계좌번호 뒤 2자리
#ACNT_PRDT_CD: "01"
#URL_BASE: "https://openapi.koreainvestment.com:9443"


#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1280529213320855574/Rj3TyDlSpGZHhipI8lAbYa3WCp49K_SevAaN7vn1s3_tP2AuizY0NNS5A-n2e5vu5Dxv"


